FROM nginx:latest

WORKDIR /home

COPY ./nginx.conf /etc/nginx/ 
COPY ./run.sh  /home

RUN apt-get update && apt-get install -y gcc spawn-fcgi libfcgi-dev; \
    chown -R nginx:nginx /etc/nginx/nginx.conf; \
    chown -R nginx:nginx /var/run/nginx.pid; \
    rm -rf /var/lib/apt/lists

USER nginx

ENTRYPOINT ["sh" , "./run.sh"]